<?php

return PhpCsFixer\Config::create()
    ->setRules([
        '@PSR2'                                     => true,
        'array_indentation'                         => true,
        'array_syntax'                              => ['syntax' => 'short'],
        'combine_consecutive_unsets'                => true,
        'method_separation'                         => true,
        'no_multiline_whitespace_before_semicolons' => true,
        'single_quote'                              => true,
        'binary_operator_spaces'                    => [
            'default' => 'align_single_space_minimal',
        ],
        'blank_line_before_return' => true,
        'braces'                   => [
            'allow_single_line_closure' => true,
        ],
        'concat_space'                       => ['spacing' => 'one'],
        'declare_equal_normalize'            => true,
        'function_typehint_space'            => true,
        'hash_to_slash_comment'              => true,
        'include'                            => true,
        'lowercase_cast'                     => true,
        'no_blank_lines_after_class_opening' => true,
        'no_blank_lines_after_phpdoc'        => true,
        'no_empty_comment'                   => true,
        'no_empty_phpdoc'                    => true,
        'no_empty_statement'                 => true,
        'no_extra_consecutive_blank_lines'   => [
            'curly_brace_block',
            'extra',
            'parenthesis_brace_block',
            'square_brace_block',
            'throw',
            'use',
        ],
        'no_leading_namespace_whitespace'             => true,
        'no_multiline_whitespace_around_double_arrow' => true,
        'no_spaces_around_offset'                     => true,
        'no_trailing_comma_in_list_call'              => true,
        'no_trailing_comma_in_singleline_array'       => true,
        'no_unneeded_control_parentheses'             => true,
        'no_unused_imports'                           => true,
        'no_whitespace_before_comma_in_array'         => true,
        'no_whitespace_in_blank_line'                 => true,
        'normalize_index_brace'                       => true,
        'object_operator_without_whitespace'          => true,
        'phpdoc_align'                                => true,
        'phpdoc_annotation_without_dot'               => true,
        'phpdoc_indent'                               => true,
        'phpdoc_inline_tag'                           => true,
        'phpdoc_no_empty_return'                      => true,
        'phpdoc_trim'                                 => true,
        'phpdoc_types'                                => true,
        'single_blank_line_before_namespace'          => true,
        'ternary_operator_spaces'                     => true,
        'trim_array_spaces'                           => true,
        'unary_operator_spaces'                       => true,
        'whitespace_after_comma_in_array'             => true,
    ])
    ->setUsingCache(false)
    ->setLineEnding("\n");
